# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Full Tank Sports
email: infol@fulltanksports.com
description: > 
  Full Tank Sports is the sports website that's going to get worse before it gets better. 
  Find articles and podcasts from people who are in no way qualified to tell you 
  anything about sports.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fulltanksports.com" # the base hostname & protocol for your site
twitter_username: fulltanksports
github_username:  dtyman

# Build settings
markdown: kramdown
